name             'tmux-latest'
maintainer       'David Pell'
maintainer_email 'davidcpell@gmail.com'
license          'all_rights'
description      'Installs/Configures tmux'
long_description 'Installs/Configures the latest version of tmux from source'
source_url       'https://github.com/davidcpell/tmux-latest'
issues_url       'https://github.com/davidcpell/tmux-latest/issues'
version          '0.1.0'
